Repository kosa-midas-woopy/Woopy_Android, pull requests merged in 2022-11, with the labels that each got.

#2 Merge(#1): Woopy 프로젝트
  .gitignore
  README.md
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/indoor/woopy_android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indoor/woopy_android/view/activity/MainActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/fragment/AllFunctionFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/fragment/HomeFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/fragment/RequestFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/fragment/StatisticsFragment.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_graph_bar_up.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_plus_circle.xml
  app/src/main/res/drawable/ic_three_line.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_all_function_fragment.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_request.xml
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/indoor/woopy_android/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: feature

#6 Merge(#5) : Status Bar 색상 변경
  .github/CODEOWNERS
  app/src/main/java/com/indoor/woopy_android/view/activity/MainActivity.kt
  app/src/main/res/drawable/bottom_nav_selected_color.xml
  app/src/main/res/drawable/ic_graph_bar_up.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_plus_circle.xml
  app/src/main/res/drawable/ic_three_line.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_select_account_type.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: style ✨

#8 Merge(#7) : 프로젝트 재구조화
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indoor/woopy_android/view/user/MainActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/user/allfunction/AllFunctionFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/user/approval/RequestFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/user/home/HomeFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/user/statistics/StatisticsFragment.kt
  app/src/main/res/layout/activity_main.xml
Labels: chore

#9 Feat : 메인 페이지 UI 작성
  app/src/main/java/com/indoor/woopy_android/view/user/home/Date.kt
  app/src/main/java/com/indoor/woopy_android/view/user/home/HomeFragment.kt
  app/src/main/java/com/indoor/woopy_android/view/user/home/WeeklyCalendarAdapter.kt
  app/src/main/res/drawable/bg_box.xml
  app/src/main/res/drawable/bg_radius_button.xml
  app/src/main/res/drawable/bg_weekly_calendar.xml
  app/src/main/res/drawable/ic_next.png
  app/src/main/res/drawable/ic_prev.png
  app/src/main/res/drawable/woopy_word_logo.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_request.xml
  app/src/main/res/layout/weekly_calendar_item.xml
Labels: feature

#11 Feat : 로그인 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indoor/woopy_android/view/SelectAccountTypeActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/admin/Activity_admin_signup.kt
  app/src/main/java/com/indoor/woopy_android/view/admin/AdminLoginActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/admin/viewmodel/AdminLoginViewModel.kt
  app/src/main/java/com/indoor/woopy_android/view/user/UserLoginActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/user/UserSignupOfficeActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/user/UserSignupUserActivity.kt
  app/src/main/java/com/indoor/woopy_android/view/user/viewmodel/UserLoginViewModel.kt
  app/src/main/java/com/indoor/woopy_android/view/user/viewmodel/UserSignupOfficeViewModel.kt
  app/src/main/java/com/indoor/woopy_android/view/user/viewmodel/UserSignupUserViewModel.kt
  app/src/main/res/drawable/bg_box.xml
  app/src/main/res/drawable/bg_radious_button.xml
  app/src/main/res/drawable/ic_admin.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/layout/activity_admin_login.xml
  app/src/main/res/layout/activity_admin_signup.xml
  app/src/main/res/layout/activity_select_account_type.xml
  app/src/main/res/layout/activity_user_login.xml
  app/src/main/res/layout/activity_user_signup_office.xml
  app/src/main/res/layout/activity_user_signup_user.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: feature

#15 Feat : 다양한 기능들 추가
  app/src/main/java/com/indoor/woopy_android/EditOptionActivity.kt
  app/src/main/java/com/indoor/woopy_android/activity_option.kt
  app/src/main/java/com/indoor/woopy_android/view/user/allfunction/AllFunctionFragment.kt
  app/src/main/res/drawable/ic_option.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/layout/activity_edit_option.xml
  app/src/main/res/layout/activity_option.xml
  app/src/main/res/layout/fragment_all_function_fragment.xml
  app/src/main/res/layout/fragment_statistics.xml
Labels: feature
